---
title: "Perception of Founders' Age in Startups"
author: "Dr Preet Deep Singh"
affiliation: "Invest India"
date: "09/09/2021"
output: 
  bookdown::pdf_document2:
    toc: no
    citation_package: natbib
    number_sections: yes
    keep_tex: yes
abstract: "Using a dataset of 150011 projects from Kickstarter, we analyse various factors that influence success of a campaign. Results show that goal amount, use of specific words in the blurb, category of project, and duration of the project are statistically significant. We also use readability tests to show that the more the readability of description more the probability of success. Our paper has prescriptive relevance for practitioners "
documentclass: "article"
editor_options: 
  chunk_output_type: console
bibliography: references.bib
link-citations: true
csl: apa.csl
---

\section{Introduction}

While traditional finance theories such as pecking order theory, predict that firms would raise debt before equity <Check Once>, the new era of companies based on new market segments and product offerings that cannot be compared to those existing, has led to a new paradigm of looking at risk and its distribution. While over 80\% of startups fail \footnote{CITE}, crowd-funding is changing the way risky enterprises are being financed. 

\subsection{About Crowdfunding}
\subsubsection{Previously}

4 types of crowd funding - Reward, Debt, Equity, Donation. In India SEBI has not allowed investors to go the equity route to invest in starups. This is because of the inherent problems in inviting public to subscribe to the shares of the company <Cite Companies Act>. Donations, if made to registered entities under section 80 (Whatever subsection) of the Income Tax Act, 1961, are exempt from income tax. Therefore if the organisation raising funds is an entity covered under the relevant sections of the Act, then the investor (donor in this case) can get a tax exemption on the money so donated. Under the reward base, the investor is promised the product. Thus this method works as a pre-order facility. While the company is assured of a minimum sale and gets cash to keep it going, the investor gets a right to get his/her hands on a product before it hits the market. <<You can cite some of many examples available here>. Debt based model is difficult to execute on a platform only mode and therefore requires more interaction between the organisation and the the creditor. However debt is an important part of funding and risk disbursement.

\subsection{About Kickstarter}
What it is, when it was founded, how much money has it already disbursed. This will come from the Datastats that it itself
shows.


\subsection{About the study}
In this paper we look at 150011 projects on Kickstarter from April, 2009 to November, 2015. Our sample includes failed, cancelled, suspended and successful projects. <Some Literature Here>. While efficient market hypothesis and familiarity bias would predict that people prefer to invest in projects that are in the same category as that of existing Unicorns \footnote{<Say Something>}; crowd-funding does not have any equity component and follows a donation or a customer based model. Under a donation model, the people who fund projects get nothing in return. Under the customer based model the people who contribute get the product or another gift depending upon the amount they have contributed. The gift is of much less worth than the contribution. Therefore, there is an emotional and altruistic angle to the whole process. We hypothesize that projects that appeal to emotion would receive more funding than those which do not. We check this by looking at the use of words that evoke emotion. Because of the presence of multiple people we cannot rule out herding. This could be owing to better information or conformation to the norms <CITE SOMETHING>. However, herding would have to be explained differently because it is in a donation/gift setting. Crowd-funding is a social network and previous record of entrepreneurs is a key determinant in the success of their projects<Cite>. There is also a strong element of reciprocity. If one entrepreneur contributes to another persons project, his/her own project is more likely to get funded<Cite>. Reciprocity alone cannot explain all results as it is less likely that every contributor is an entrepreneur looking to raise funds. Our results indicate that certain words such as mother, son, love, dream, student have an effect on the success, plausibly because they appeal to an emotion or to pity.

\section{Literature}

Mollick (2014) look at the dynamics underlying the success of crowdfunding projects. They show that personal effects, project quality and geography are related to the success of the project. They also find that most projects (75\%) deliver projects later than the promised date.


Inbar and Basrzilay (2014) find evidence of reciprocity. They use data from Kickstarter to show that entrepreneurs who have backed projects earlier are more likely to get funded. Using network theory they advise that backing projects is a good strategy that contributes to success of your own project. It is possible that they find this relation due to learning. If someone backs multiple projects, he/she is likely to have learnt what works and what not. If those learnings are incorporated in his/her own projects then the success of that project would reflect confounding effects of network theory and learning by being in the system. 


Bellaframme, Lambert and Schewienbacher (2014) find that crowdfunding initiatives that are presented as non-profit organisations tend to be more successful at raising funds after controlling for other factors. They say that this is in line with contract failure literature that purports that due to reduced focused on projects, NPOs can raise money easily for initiatives in which the general public is interested.
We extend this literature by looking at the level to which a project can connect with the people. <Extend here>


Ahlers et al(2012) examine signals that induce providers of finance to commit to crowdfunding projects. They find that financial roadmaps, risk factors and internal governance are key factors that determine the success of a crowdfunding project.


Similar but not same is an analysis of Lui (2013) on microloans where he finds that on Prosper.com \footnote{a microloan website} there is herding but it is not irrational herding. Lender make informed decisions after looking at the past record of borrowers and borrowers traits-favourable or not- are amplified.


\section{Method}

\subsection{Data}
Our sample includes 171,436 observations. After removing projects for which we do not have complete data, we are left with 150011 observations. Table 1 gives a summary of the data. Our data spans 80 months ranging from April, 2009 to November, 2015. We have data from 16 categories viz. Theatre, Design, Fashion, Technology, Film and Video Games, Publishing, Crafts, Arts, Music, Comics, Food, Photography, Others, Journalism and Dance. The projects have one of four states: cancelled, suspended, failed or successful. Successful and failed are the two dominant categories. The projects on Kickstarter can be from any nation and therefore can pertain to different currencies. Projects in our sample span 10 currencies GBP, USD, CAD, AUD, NZD, NOK, EUR, CHF, DKK and SEK. We use the conversion rate as on December 21, 2015 to convert all amounts into USD.

\subsection{Various Steps}

\subsubsection{Timing}
We look at the month in which the project is launched and the relevant impact it has on the probability of success of the project.

\subsubsection{Words}
We look at words that are most likely to appeal to emotion or pity. In case a particular word is present we assign a dummy of 1 to that particular project. In case more than one such word is present in the project blurb, we add the two. Thus the coefficient on the SumOfWords variable is indicative of the effect of using both the words over and above the effect of any one of those words. We use words such as mother, baby, kids, environment, dream, amputee, accident, death, friend, love etc.\footnote{For a complete list of words that we ran, please refer Annexure <Refer>}. The dependent variable is coded as 1, in case the project is successful and 0 in case the project is not successful. Because of the binary nature of the variable, we use the following logit model:

\begin{math}
$$ Success = \alpha + \beta_{1} Word1 + \beta_{2} Word2 + \beta_{3} SumOfWords +Control+\epsilon    $$
\end{math}

\subsubsection{Herding}
We use a relatively simple method to detect herding. We segregate the data based on categories and summarise it by month of the project deadline. As a robustness check we use month of project launch date but our results remain similar. Once summarised, we use a rolling window regression to look at the effect of number of backers in a month on the number of backers in the previous 12 months. We also regress the amount of money pledged in a month on the amount of money pledged in the previous  twelve months. There are 68 cases for regression in each category. We report aggregate results for all the categories. We use the following regressions:

\begin{math}
%	\begin{center}
$$ Backers_{13} = \alpha + \beta_{1}Backers_{1-12}+\beta_{2}Control  +\epsilon $$ \\
$$ Sum_{13} = \alpha + \beta_{1}Sum_{1-12}+\beta_{2}Control +\epsilon $$			
%	\end{center}
\end{math}			

\subsubsection{Readability}
We use 26 different readability tests. It has an impact.
<Put literature here>
\section{Results and Discussion}
Readability affects the probability of success. 
Currency also contributes. Maybe due to familiarity. 
The time for which it is open is also a significant factor. 
The amount it wishes to raise. 
The use of certain words in the blurb. 
Month and category also have a role to play. 
Herding exists and the money contributed to projects in the previous months is a significant determinant. 

\section{Conclusion}

In this study we show evidence of herding. Our hypotheses regarding emotion appeal is vindicated even after controlling for multiple factors. Since crowdfunding is in line with donations and appeals to the benevolence rather than to greed, a different lens is needed to look at the motivation of those who pledge money, beyond reciprocity.
Change and all A general time control or something

\newpage
\section*{Bibliography}